--
-- Type: TABLE; Owner: BIOMART; Name: BIO_ASY_ANALYSIS_EQTL_TOP50
--
 CREATE TABLE "BIOMART"."BIO_ASY_ANALYSIS_EQTL_TOP50"
  (	"BIO_ASSAY_ANALYSIS_ID" NUMBER(18,0) NOT NULL ENABLE,
"ANALYSIS" NVARCHAR2(500),
"CHROM" VARCHAR2(4 BYTE),
"POS" NUMBER,
"RSGENE" VARCHAR2(255 BYTE),
"RSID" NVARCHAR2(50),
"PVALUE" BINARY_DOUBLE,
"LOGPVALUE" BINARY_DOUBLE,
"GENE" VARCHAR2(50 BYTE),
"EXTDATA" VARCHAR2(4000 BYTE),
"RNUM" NUMBER,
"INTRONEXON" VARCHAR2(10 BYTE),
"RECOMBINATIONRATE" NUMBER(18,6),
"REGULOME" VARCHAR2(10 BYTE)
  ) SEGMENT CREATION DEFERRED
 TABLESPACE "TRANSMART" ;

