-- NOTE: not in i2b2 schema for i2b2demo data - version 1.7 - 02Dec2014 - Terry Weymouth

--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: HILOSEQUENCES
--
 CREATE TABLE "I2B2DEMODATA"."HILOSEQUENCES" 
  (	"SEQUENCENAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"HIGHVALUES" NUMBER(*,0) NOT NULL ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

