-- NOTE: not in i2b2 schema for i2b2demo data - version 1.7 - 02Dec2014 - Terry Weymouth

--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: JMS_USERS
--
 CREATE TABLE "I2B2DEMODATA"."JMS_USERS" 
  (	"USERID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
"PASSWD" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
"CLIENTID" VARCHAR2(128 BYTE), 
 PRIMARY KEY ("USERID")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

