-- NOTE: not in i2b2 schema for i2b2demo data - version 1.7 - 02Dec2014 - Terry Weymouth

--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: JMS_TRANSACTIONS
--
 CREATE TABLE "I2B2DEMODATA"."JMS_TRANSACTIONS" 
  (	"TXID" NUMBER(*,0)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

