-- NOTE: not in i2b2 schema for i2b2demo data - version 1.7 - 02Dec2014 - Terry Weymouth

--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: MAP
--
 CREATE TABLE "I2B2DEMODATA"."MAP" 
  (	"SUBJECT_ID" VARCHAR2(100 BYTE), 
"SMAPLE_ID" VARCHAR2(100 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

