-- NOTE: not in i2b2 schema for i2b2demo data - version 1.7 - 02Dec2014 - Terry Weymouth

--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: PATIENT_TRIAL
--
 CREATE TABLE "I2B2DEMODATA"."PATIENT_TRIAL" 
  (	"PATIENT_NUM" NUMBER, 
"TRIAL" VARCHAR2(30 BYTE), 
"SECURE_OBJ_TOKEN" VARCHAR2(50 BYTE)
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

