-- NOTE: not in i2b2 schema for i2b2demo data - version 1.7 - 02Dec2014 - Terry Weymouth

--
-- Type: TABLE; Owner: I2B2DEMODATA; Name: SAMPLE_DIMENSION
--
 CREATE TABLE "I2B2DEMODATA"."SAMPLE_DIMENSION" 
  (	"SAMPLE_CD" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
 CONSTRAINT "SAMPLE_DIMENSION_PK" PRIMARY KEY ("SAMPLE_CD")
 USING INDEX
 TABLESPACE "TRANSMART"  ENABLE
  ) SEGMENT CREATION IMMEDIATE
 TABLESPACE "TRANSMART" ;

