--
-- Type: TYPE; Owner: BIOMART_USER; Name: CONCEPT_CD_TAB
--
  CREATE OR REPLACE TYPE "BIOMART_USER"."CONCEPT_CD_TAB" IS TABLE OF VARCHAR2(50)
/

--
-- Type: TYPE; Owner: BIOMART_USER; Name: PATIENTS_TAB
--
  CREATE OR REPLACE TYPE "BIOMART_USER"."PATIENTS_TAB" IS TABLE OF NUMBER(10,0)
/

--
-- Type: TABLE; Owner: BIOMART_USER; Name: SESSION_MULTISETS_OF_INTEGERS
--
CREATE GLOBAL TEMPORARY TABLE SESSION_MULTISETS_OF_INTEGERS (
  ID NUMBER(38,0),
  MID NUMBER(10,0) NOT NULL
) ON COMMIT PRESERVE ROWS;
--
-- Lock statistics
--
begin
    dbms_stats.lock_table_stats('BIOMART_USER', 'SESSION_MULTISETS_OF_INTEGERS');
end;
/

--
-- Type: TABLE; Owner: BIOMART_USER; Name: SESSION_MULTISETS_OF_STRINGS
--
CREATE GLOBAL TEMPORARY TABLE SESSION_MULTISETS_OF_STRINGS (
  ID VARCHAR2(4000),
  MID NUMBER(10,0) NOT NULL
) ON COMMIT PRESERVE ROWS;
--
-- Lock statistics
--
begin
    dbms_stats.lock_table_stats('BIOMART_USER', 'SESSION_MULTISETS_OF_STRINGS');
end;
/
