--
-- Type: TABLE; Owner: TM_CZ; Name: TMP_ANALYSIS_COUNT_EQTL
--
 CREATE GLOBAL TEMPORARY TABLE "TM_CZ"."TMP_ANALYSIS_COUNT_EQTL"
  (	"TOTAL" NUMBER,
"BIO_ASSAY_ANALYSIS_ID" NUMBER NOT NULL ENABLE
  ) ON COMMIT PRESERVE ROWS ;

